name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: DEBUG Show first lines of private key
        run: |
          echo "=== FIRST 5 LINES OF REMOTE_KEY ==="
          echo "${{ secrets.REMOTE_KEY }}" | head -n 5

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER2 }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            echo "📁 Клонируем проект если не существует"
            if [ ! -d /var/www/fastuser/data/www/trimbg.pro ]; then
              git clone git@github.com:Bogdan-K-A/trimbg.git /var/www/fastuser/data/www/trimbg.pro
            fi

            cd /var/www/fastuser/data/www/trimbg.pro

            echo "🔄 Обновляем код"
            git pull origin main

            echo "📦 Устанавливаем зависимости"
            npm install

            echo "🏗️ Сборка фронтенда"
            npm run build

            echo "📦 Устанавливаем зависимости backend"
            cd backend
            npm install
            cd ..

            echo "🚀 Запускаем через PM2"
            pm2 startOrReload ecosystem.config.js
